### ISSUE TITLE
With quarkus 3.11.0 I get NoClassDefFoundError on manual MockServerClient init

### ISSUE THREAD

**Issue by HerrDerb** [quarkiverse/quarkus-mockserver#149]
Mockserver seems to use some transitive dependencies from quarkus which seems to be removed in 3.11.0

* 'io.swagger.core.v3:swagger-core'
* 'com.github.fge:jackson-coreutils'

```
io.swagger.v3.oas.models.media.Schemajava.lang.NoClassDefFoundError: io/swagger/v3/oas/models/media/Schema
	at org.mockserver.serialization.serializers.schema.SchemaSerializer.<init>(SchemaSerializer.java:25)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.string.NottableStringSerializer.<clinit>(NottableStringSerializer.java:24)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.body.JsonSchemaBodyDTOSerializer.<clinit>(JsonSchemaBodyDTOSerializer.java:21)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.body.JsonSchemaBodySerializer.<clinit>(JsonSchemaBodySerializer.java:21)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.body.JsonBodyDTOSerializer.<clinit>(JsonBodyDTOSerializer.java:22)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.body.JsonBodySerializer.<clinit>(JsonBodySerializer.java:21)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.request.OpenAPIDefinitionDTOSerializer.<clinit>(OpenAPIDefinitionDTOSerializer.java:19)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.request.OpenAPIDefinitionSerializer.<clinit>(OpenAPIDefinitionSerializer.java:19)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.expectation.OpenAPIExpectationDTOSerializer.<clinit>(OpenAPIExpectationDTOSerializer.java:19)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.serializers.expectation.OpenAPIExpectationSerializer.<clinit>(OpenAPIExpectationSerializer.java:19)
	at org.mockserver.serialization.ObjectMapperFactory.addSerializers(ObjectMapperFactory.java:203)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:164)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:56)
	at org.mockserver.serialization.deserializers.string.NottableStringDeserializer.<clinit>(NottableStringDeserializer.java:25)
	at org.mockserver.serialization.ObjectMapperFactory.addDeserializers(ObjectMapperFactory.java:170)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:163)
	at org.mockserver.serialization.ObjectMapperFactory.<clinit>(ObjectMapperFactory.java:49)
	at org.mockserver.serialization.RequestDefinitionSerializer.<init>(RequestDefinitionSerializer.java:36)
	at org.mockserver.client.MockServerClient.<init>(MockServerClient.java:85)
	at org.mockserver.client.MockServerClient.<init>(MockServerClient.java:134)
```

```
java.lang.NoClassDefFoundError: com/github/fge/jackson/JacksonUtils
	at org.mockserver.serialization.ExpectationSerializer.deserializeArray(ExpectationSerializer.java:170)
	at org.mockserver.serialization.ExpectationSerializer.deserializeArray(ExpectationSerializer.java:158)
	at org.mockserver.client.MockServerClient.upsert(MockServerClient.java:1517)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:84)
```

**Comment by HerrDerb** [comment]
Hm wait something is not right, it is not that straight forward. Will reopen if I can hold my finger on it.

**Comment by PhilippParis** [comment]
hI!
i still have that issue with the newest quarkus version. is there a fix?
